[package]
name = "schnorr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin_hashes = "0.11.0"
rand = "0.8.5"
secp256k1 = { version = "0.25.0", features = ["rand-std", "bitcoin-hashes-std"] }
