name: Deploy binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Deploy packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # - aarch64-unknown-linux-gnu
          # - armv7-unknown-linux-gnueabihf
          # - i686-unknown-linux-gnu
          # - i686-unknown-linux-musl
          # - arm-unknown-linux-gnueabi
          - x86_64-unknown-linux-gnu
          # - x86_64-unknown-linux-musl
          # - x86_64-unknown-netbsd
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies required to build it
      - name: Install ssl, musl, wget...
        run: |
          sudo apt-get update
          sudo apt-get install -y wget pkg-config libssl-dev musl-tools
          sudo wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb

      # Setup Toolchain
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      # - name: Build target
      #   uses: actions-rs/cargo@v1
      #   with:
      #     use-cross: true
      #     command: build
      #     args: --release --target ${{ matrix.target }}

      # Install cross to build cross-compiling
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      # Build with cross
      - name: Build target
        run: cross build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../package-${{ matrix.target }}.tar.gz relay client
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
          files: "package-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
